version: 2.1

jobs:
  setup-and-test:
    docker:
     - image: circleci/python:3.8  # Use the base image that suits your project

    # machine:
    #   image: ubuntu-2204:2022.07.1

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install pytest && pip install numpy
          # working_directory: Front-end/expense-management-frontend
      - run:
          name: Run Tests
          command: pytest test_sparse_recommender.py
          # working_directory: Front-end/expense-management-frontend

workflows:
  Setup_and_Test:
    jobs:
      - setup-and-test
